# Generated by Django 3.1.3 on 2020-12-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201210_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CartDetails',
            new_name='CartDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
